#!/bin/bash

set -euo pipefail

docker build -t manylinux-cuda -f docker/cuda-on-manylinux.Dockerfile .
docker run --rm -v $(pwd):/project -w /project manylinux-cuda \
    AIMDO_EXTRA_CFLAGS=-Werror bash ./scripts/build-linux-aimdo.sh
