# comfy-aimdo Windows ROCm local build script
# Requires: Visual Studio, Git, and ROCm SDK
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = $PSScriptRoot
function F([string]$p) { $p.Replace('\','/') }  # forward-slash paths for clang rsp

# ── ROCm ───────────────────────────────────────────────────────────────────────
$rocmBase = if ($env:VIRTUAL_ENV -and (Test-Path "$env:VIRTUAL_ENV\Lib\site-packages\_rocm_sdk_core")) {
    "$env:VIRTUAL_ENV\Lib\site-packages\_rocm_sdk_core"
} elseif ($env:HIP_PATH)  { $env:HIP_PATH  } elseif ($env:ROCM_PATH) { $env:ROCM_PATH }
if (-not $rocmBase -or -not (Test-Path "$rocmBase\include\hip")) {
    throw "ROCm not found. Set HIP_PATH/ROCM_PATH or activate a venv with _rocm_sdk_core."
}
$clang = "$rocmBase\lib\llvm\bin\clang.exe"
if (-not (Test-Path $clang)) { throw "clang.exe not found at: $clang" }
Write-Host "ROCm: $rocmBase"

# ── Detours ────────────────────────────────────────────────────────────────────
$detoursDir = "$root\detours"
if (-not (Get-Command git -ErrorAction SilentlyContinue)) { throw "git not found. Please install Git and ensure it is on PATH." }
if (Test-Path $detoursDir) { Remove-Item -Recurse -Force $detoursDir }
git clone -q --depth 1 https://github.com/microsoft/Detours.git $detoursDir

$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { throw "vswhere.exe not found. Is Visual Studio installed?" }
$vcvars  = "$(& $vswhere -latest -property installationPath)\VC\Auxiliary\Build\vcvars64.bat"
$bat = [IO.Path]::Combine([IO.Path]::GetTempPath(), [IO.Path]::GetRandomFileName() + ".bat")
"@echo off`ncall `"$vcvars`" || exit /b 1`ncd /d `"$detoursDir\src`"`nnmake" | Set-Content $bat -Encoding ASCII
cmd /c $bat
Remove-Item $bat
if ($LASTEXITCODE -ne 0) { throw "Detours build failed (vcvars or nmake error)" }

# ── Compile ────────────────────────────────────────────────────────────────────
# use pure command to build: pwsh will handel *.c expanding and \ slash
& $clang src/*.c src-win/*.c -xc --target=x86_64-pc-windows-msvc `
    -shared -O3 -D__HIP_PLATFORM_AMD__ -Wno-unused-command-line-argument `
    -I"$rocmBase/include" -I"$detoursDir/include" -Isrc `
    -L"$rocmBase/lib" -L"$detoursDir/lib.X64" `
    -lamdhip64 -ldxgi -ldxguid -ldetours `
    -o"comfy_aimdo/aimdo_rocm.dll"
if ($LASTEXITCODE -ne 0) { throw "Build failed (exit code $LASTEXITCODE)" }

Remove-Item -Recurse -Force $detoursDir

# ── Generate _rocm_init.py (same as PyTorch/TheRock) ───────────────────────────
# Version is captured at build time for compatibility checking at runtime
$rocmSdkVersion = (& python -m rocm_sdk version 2>$null) -replace '\s',''
if (-not $rocmSdkVersion) { $rocmSdkVersion = "" }
Write-Host "ROCm SDK version: $rocmSdkVersion"

$rocmInitContent = @"
# Auto-generated by build-rocm-local_win.ps1 (same pattern as PyTorch/TheRock)

def initialize():
    import rocm_sdk
    rocm_sdk.initialize_process(
        preload_shortnames=['amdhip64'],
        check_version='$rocmSdkVersion')
"@

Set-Content -Path "$root\comfy_aimdo\_rocm_init.py" -Value $rocmInitContent -Encoding UTF8
Write-Host "Generated: comfy_aimdo\_rocm_init.py"
Write-Host "Build successful: comfy_aimdo\aimdo_rocm.dll"
